name: false
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - missingno
  - Ipython
  - bqplot
  - ipywidgets
  - xlrd==1.2
  - bokeh
  - pip:
    - bqplot==0.12.21
    - nbserverproxy==0.8.8
    - jupyter-server-proxy==1.2.0
    - streamlit==0.52.2


