name: false
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - missingno
  - Ipython
  - bqplot
  - ipywidgets
  - xlrd==1.2
  - bokeh
  - pip:
    - bqplot==0.12.21
    - nbserverproxy
    - jupyter-server-proxy


